name: Replace Repo Name in JS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace API_KEY in JavaScript file
        run: |
          # The | character denotes a multiline command
          # The 'sed' command is used to find and replace text
          # s/API_KEY/ replace API_KEY with the value of the GH_API_KEY secret
          # g/ specifies a global replacement
          # The file is specified at the end
          sed -i "s|API_KEY|${{ secrets.GH_API_KEY }}|g" path/to/your/file.js

      - name: Display the modified file
        run: |
          cat LoveStory/main.js
